Repository yorkie-team/yorkie-js-sdk, pull requests merged in 2021-03, with the labels that each got.

#146 Handle Object.keys, Object.values and Object.entries
  src/document/json/object.ts
  src/document/proxy/object_proxy.ts
  test/document/document_test.ts
Labels: enhancement 🌟

#148 Add type parameter to Document
  src/core/client.ts
  src/document/document.ts
  src/document/proxy/proxy.ts
  src/yorkie.ts
  test/document/document_test.ts
Labels: enhancement 🌟

#154 Define the event types strictly
  examples/index.html
  examples/quill.html
  examples/util.js
  src/core/client.ts
  src/document/document.ts
  src/document/operation/select_operation.ts
  src/yorkie.ts
  test/helper/helper.ts
  test/yorkie_test.ts
Labels: cleanup 🧹

#158 Exchange the names of getRootObject and getRoot
  examples/drawing.html
  examples/index.html
  examples/quill.html
  src/document/document.ts
  test/api/converter_test.ts
  test/document/document_test.ts
  test/yorkie_test.ts
Labels: cleanup 🧹

#157 Support for null values
  src/api/converter.ts
  src/document/json/primitive.ts
  test/document/document_test.ts
  test/document/json/primitive_test.ts
  test/yorkie_test.ts
Labels: enhancement 🌟

#159 Add primitive tests
  test/document/json/primitive_test.ts
Labels: cleanup 🧹

#161 Clean up element caches in root.ts
  src/document/change/context.ts
  src/document/json/root.ts
  src/document/operation/add_operation.ts
  src/document/operation/edit_operation.ts
  src/document/operation/remove_operation.ts
  src/document/operation/rich_edit_operation.ts
  src/document/operation/set_operation.ts
  src/document/proxy/array_proxy.ts
  src/document/proxy/object_proxy.ts
  test/document/json/root_test.ts
Labels: cleanup 🧹

#162 Pass paths to change events
  src/document/document.ts
  src/document/json/array.ts
  src/document/json/element.ts
  src/document/json/object.ts
  src/document/json/rga_tree_list.ts
  src/document/json/rht_pq_map.ts
  src/document/json/root.ts
  src/document/operation/add_operation.ts
  src/document/operation/edit_operation.ts
  src/document/operation/increase_operation.ts
  src/document/operation/move_operation.ts
  src/document/operation/operation.ts
  src/document/operation/remove_operation.ts
  src/document/operation/rich_edit_operation.ts
  src/document/operation/select_operation.ts
  src/document/operation/set_operation.ts
  src/document/operation/style_operation.ts
  test/document/document_test.ts
  test/document/json/root_test.ts
Labels: enhancement 🌟

#160 Apply `require-jsdoc`
  .eslintrc.js
  package-lock.json
  package.json
  src/api/converter.ts
  src/core/client.ts
  src/document/change/change.ts
  src/document/change/change_id.ts
  src/document/change/change_pack.ts
  src/document/change/context.ts
  src/document/checkpoint/checkpoint.ts
  src/document/document.ts
  src/document/json/array.ts
  src/document/json/counter.ts
  src/document/json/element.ts
  src/document/json/object.ts
  src/document/json/plain_text.ts
  src/document/json/primitive.ts
  src/document/json/rga_tree_list.ts
  src/document/json/rga_tree_split.ts
  src/document/json/rht.ts
  src/document/json/rht_pq_map.ts
  src/document/json/rich_text.ts
  src/document/json/root.ts
  src/document/key/document_key.ts
  src/document/operation/add_operation.ts
  src/document/operation/edit_operation.ts
  src/document/operation/increase_operation.ts
  src/document/operation/move_operation.ts
  src/document/operation/operation.ts
  src/document/operation/remove_operation.ts
  src/document/operation/rich_edit_operation.ts
  src/document/operation/select_operation.ts
  src/document/operation/set_operation.ts
  src/document/operation/style_operation.ts
  src/document/proxy/array_proxy.ts
  src/document/proxy/counter_proxy.ts
  src/document/proxy/object_proxy.ts
  src/document/proxy/proxy.ts
  src/document/proxy/rich_text_proxy.ts
  src/document/proxy/text_proxy.ts
  src/document/time/ticket.ts
  src/util/error.ts
  src/util/heap.ts
  src/util/llrb_tree.ts
  src/util/logger.ts
  src/util/observable.ts
  src/util/splay_tree.ts
  src/util/uuid.ts
Labels: cleanup 🧹, documentation 📔
