Repository yorkie-team/yorkie-js-sdk, pull requests merged in 2023-08, with the labels that each got.

#616 Change 'Documents' from plural to singular in DocEvent
  public/util.js
  src/api/yorkie/v1/resources.proto
  src/api/yorkie/v1/resources_pb.d.ts
  src/api/yorkie/v1/resources_pb.js
  src/api/yorkie/v1/yorkie_grpc_web_pb.js
  src/api/yorkie/v1/yorkie_pb.js
  src/client/client.ts
  src/document/document.ts
  src/yorkie.ts
Labels: cleanup 🧹, protocol changed 📝

#611 Concurrent case handling for Yorkie.tree
  public/util.js
  src/api/converter.ts
  src/api/yorkie/v1/resources.proto
  src/api/yorkie/v1/resources_pb.d.ts
  src/api/yorkie/v1/resources_pb.js
  src/api/yorkie/v1/yorkie.proto
  src/api/yorkie/v1/yorkie_grpc_web_pb.js
  src/api/yorkie/v1/yorkie_pb.d.ts
  src/api/yorkie/v1/yorkie_pb.js
  src/client/client.ts
  src/document/crdt/tree.ts
  src/document/document.ts
  src/document/json/tree.ts
  src/document/operation/tree_edit_operation.ts
  src/document/operation/tree_style_operation.ts
  src/util/index_tree.ts
  src/yorkie.ts
  test/integration/tree_test.ts
  test/unit/document/crdt/tree_test.ts
Labels: protocol changed 📝

#627 Change TreeNode to have IDs instead of insPrev, insNext
  src/api/converter.ts
  src/api/yorkie/v1/resources.proto
  src/api/yorkie/v1/resources_pb.d.ts
  src/api/yorkie/v1/resources_pb.js
  src/api/yorkie/v1/yorkie_grpc_web_pb.js
  src/document/crdt/tree.ts
  test/integration/tree_test.ts
Labels: protocol changed 📝

#622 Remove select operation from text
  src/api/converter.ts
  src/document/crdt/rga_tree_split.ts
  src/document/crdt/text.ts
  src/document/json/text.ts
  src/document/operation/select_operation.ts
Labels: cleanup 🧹
